data = [
    {
        "id": 1, 
        "gare": "Juvisy", 
        "paniers": true, 
        "jour": "Jeudi", 
        "horaires": "16h00 à 20h00", 
        "A": false, 
        "B": false, 
        "C": true, 
        "D": true, 
        "E": false, 
        "tram": false, 
        "M1": false, 
        "M4": false, 
        "M5": false,
        "M7": false,
        "M14": false,  
        "bornes": 20, 
        "Wifi": false, 
        "proprete2023": 92.5, 
        "proprete2022": 97.9, 
        "proprete2021": 94.2, 
        "proprete2020": 91, 
        "proprete2019": 89, 
        "piano": false
    },

    {
        "id": 2, 
        "gare": "Bondy", 
        "paniers": true, 
        "jour": "Mercredi", 
        "horaires": "16h00 à 20h00", 
        "A": false, 
        "B": false, 
        "C": false, 
        "D": false, 
        "E": true, 
        "tram": true, 
        "M1": false, 
        "M4": false, 
        "M5": false,
        "M7": false,
        "M14": false, 
        "bornes": 9, 
        "Wifi": true, 
        "proprete2023": 91.5, 
        "proprete2022": 91.9, 
        "proprete2021": 91.2, 
        "proprete2020": 89.6, 
        "proprete2019": 87, 
        "piano": true
    },

    {
        "id": 3, 
        "gare": "Gare de l'Est", 
        "paniers": true, 
        "jour": "Jeudi", 
        "horaires": "16h00 à 19h00", 
        "A": false, 
        "B": false, 
        "C": false, 
        "D": false, 
        "E": true, 
        "R": false,
        "tram": false,
        "M1": false, 
        "M4": true, 
        "M5": true, 
        "M7": true, 
        "M14": false,
        "bornes": 8, 
        "Wifi": true, 
        "proprete2023": 94.5, 
        "proprete2022": 95.9, 
        "proprete2021": 93.2, 
        "proprete2020": 97, 
        "proprete2019": 92, 
        "piano": true
    },

    {
        "id": 4, 
        "gare": "Gare de Lyon", 
        "paniers": true, 
        "jour": "Lundi", 
        "horaires": "16h30 à 20h00", 
        "A": true, 
        "B": false, 
        "C": false, 
        "D": true, 
        "E": false, 
        "R": true, 
        "tram": false, 
        "M1": true, 
        "M4": false, 
        "M5": false,
        "M7": false,
        "M14": true, 
        "bornes": 6, 
        "Wifi": true, 
        "proprete2023": 91.5, 
        "proprete2022": 94.9, 
        "proprete2021": 88.2, 
        "proprete2020": 92, 
        "proprete2019": 92, 
        "piano": true 
    },

    {
        "id": 5, 
        "gare": "Choisy le Roi", 
        "paniers": false, 
        "jour": "Jeudi", 
        "horaires": "16h00 à 19h30", 
        "A": false, 
        "B": false, 
        "C": true, 
        "D": false, 
        "E": false, 
        "R": false, 
        "tram": false, 
        "M1": false, 
        "M4": false, 
        "M5": false,
        "M7": false,
        "M14": false, 
        "bornes": 6, 
        "Wifi": true, 
        "proprete2023": 91.5, 
        "proprete2022": 93.6, 
        "proprete2021": 83.2, 
        "proprete2020": 90, 
        "proprete2019": 92, 
        "piano": false
    }
]